language: java
script:
  #Lance les tests
  - mvn clean verify --file ./simple-api/pom.xml

  #Connecte à Docker avec les variables d'env
  #enregistrées au préalable sur Travis
  - docker login -u $user -p $password

  #Build
  - docker build -t $user/myproject:database database
  - docker build -t $user/myproject:httpd httpd
  - docker build -t $user/myproject:simple-api simple-api


  #Push sur Docker hub
  - docker push $user/myproject:database
  - docker push $user/myproject:httpd
  - docker push $user/myproject:simple-api



  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install
  sonar:sonar -Dsonar.projectKey=devops-2020

addons:
sonarcloud:
organization: "devops-epf"
token: "$SONARCLOUD_TOKEN"

